### ISSUE TITLE
Secrets being printed when using basic auth

### ISSUE THREAD

**Issue by lopezator** [gomods/athens#1046] opened 2019-01-24 11:49 UTC
**Describe the bug**

When using athens + basic auth and any error occur, secrets are being printed on logs (anybody can see them on a failed CI failed build).

**Error Message**

With athens down, the error trying to use the proxy would be:

```console
go: google.golang.org/genproto@v0.0.0-20190111180523-db91494dd46c: unexpected status (https://myuser:mypassword@athens.mydomain.com/google.golang.org/genproto/@v/v0.0.0-20190111180523-db91494dd46c.info): 503 Service Unavailable
```

**To Reproduce**

Use basic auth against a down athens server.

**Expected behavior**

Secrets not being printed.

**Comment by marwan-at-work** [comment] 2019-01-24 15:31
That error comes from the Go command directly and hiding it would mean hiding all errors which makes it impossible to know why something failed when running a build.
The issue is mainly about the fact that Go does not have a header-based auth mechanism yet. See https://github.com/golang/go/issues/26232

There’s an ugly hack potentially: scan the error string, and concatenate the basic auth into the URL format and see if the two match, then obfuscate it.

Or we can wait until Go will solve auth by 1.13 and we can hopefully remove the basic-auth all together. 

Solving this issue would not make basic auth with Athens 100% secure, because basic auth is part of the URL, and URLs are expected to be viewable, for example if you run `go env` the GOPROXY variable will always be printed. So, if you really want to hide Athens, the best way is to put it behind a VPN until Go 1.13 comes out. 

Closing the issue, but if anyone's interested in the ugly hack feel free to discuss/reopen. Thanks!

**Closed by marwan-at-work** 2019-01-24 15:31 UTC

**Comment by lopezator** [comment] 2019-03-06 08:37
I link to the main go repo issue in case someone reaches here:

https://github.com/golang/go/issues/30610
