### ISSUE TITLE
Ensure storage tests can run without intermittent failures

### ISSUE THREAD

**Issue by arschles** [gomods/athens#488] opened 2018-08-15 01:12 UTC
Storage tests right now run in parallel against the same shared datastore, so intermittent failures can happen due to race conditions (@marwan-at-work mentioned that he's seen some). 

We should think about whether we can do something to make this more "foolproof". One idea is to use [testify/suite](https://godoc.org/github.com/stretchr/testify/suite)'s [`SetupTest`](https://godoc.org/github.com/stretchr/testify/suite#SetupTestSuite) and [`TearDownTest`](https://godoc.org/github.com/stretchr/testify/suite#TearDownTestSuite) functions to provide each test with its own database (or whatever is appropriate for the given storage driver)

Another option is to run with `go test -p 1 ...` to ensure _all_ tests don't run in parallel (this is what the `buffalo` CLI does). I don't feel like that's an ideal solution, but it works for them.

cc/ @michalpristas @robjloranger @marwan-at-work since we've all talked about testing in one way or another recently

**Comment by marwan-at-work** [comment] 2018-08-15 02:52
@arschles should this issue apply to all storages and not just RDMBS? 

In any case, I think each test can get an "acquire" and "clean" functions as arguments so that each test can have its own namespace inside the Storage and a way to clean up afterwards. 

This not only allows running tests in parallel, but running the tests again on the same DB instance. 

PS. for RDBMS, seems like we're on the path to remove the whole storage anyway: https://github.com/gomods/athens/issues/423#issuecomment-412160092?

**Comment by michalpristas** [comment] 2018-08-15 06:48
i like `-p 1` solution from Buffalo. I'm not a fan of tweaking code just to make tests work.

**Comment by marwan-at-work** [comment] 2018-08-15 13:10
@michalpristas if you run storage tests twice in a row, they fail. Because the DB doesn't get cleaned up after the first time, is that ok? If so, we should at least document that "you can only run the tests once, otherwise you have to clean the DB manually".

**Comment by michalpristas** [comment] 2018-08-15 13:19
yes, I agree with the cleanup at the end of the tests, this is a must as well.
But if tests operate on the same collection we should keep them running sequentially

**Comment by fedepaol** [comment] 2018-08-19 21:47
Can I work on this? Are we talking about the tests for `pkg/storage` right?

**Comment by arschles** [comment] 2018-08-20 16:53
@fedepaol absolutely. And yes, we're talking primarily about `pkg/storage` tests, but this also applies to tests in `cmd/proxy/actions` because they use the storage drivers in pkg/storage

**Comment by fedepaol** [comment] 2018-08-20 17:08
OMG, my first officially assigned issue!

**Comment by arschles** [comment] 2018-08-20 18:08
yessss! 💯

**Comment by fedepaol** [comment] 2018-08-22 21:35
Need some help.

If I look at https://github.com/gomods/athens/blob/master/pkg/storage/storage_tests/module_storage/storage_test.go#L71 that's the only test function, so even if we enable running the tests in parallel, all the storage tests are there. Which means that the storage tests are called *sequentially*

Moreover, each storage has its own datastore (like mongo, fs, etc). What am I missing?

**Comment by robjloranger** [comment] 2018-08-22 21:56
I think mostly you need to make sure each test suite cleans up after itself. One of the issues is that an artifact from a previous year could remain to interfere with a subsequent test.

**Comment by manugupt1** [comment] 2018-08-23 22:14
@fedepaol We have removed RDBMS package from master. Can you verify if that is the case again? I checked it again and I did not find it.

**Comment by fedepaol** [comment] 2018-08-23 22:34
@manugupt1 what I meant here is that *before* we had tests for rdbms with no cleanup, which *might have* been the cause of this issue. 

I linked an old revision to show that. Now that they are gone with the rdbms package, this issue could not be a problem anymore.

**Comment by manugupt1** [comment] 2018-08-23 22:36
@fedepaol Ah okay! So, this might be fixed!

**Comment by devdinu** [comment] 2018-08-24 01:39
We should cleanup, but even after we do that, might hit into race condition. while cleaning we can't drop table, but clear its own records. 

we should have records different for each storage and cases. eg: `storage_name_operation_module`, if we've same module with save and list cleanup might happen before other completes.

**Comment by fedepaol** [comment] 2018-08-24 06:58
@devdinu  Not sure race conditions are the problem. As I wrote before, there is only one test function that runs all the tests sequentially, one storage at the time, which is https://github.com/gomods/athens/blob/master/pkg/storage/storage_tests/module_storage/storage_test.go#L71

**Comment by marpio** [comment] 2018-08-28 10:34
@fedepaol is there anything to do here or can we close it?

**Comment by fedepaol** [comment] 2018-08-28 10:35
@marpio I think this can be closed

**Closed** 2018-08-28 10:48 UTC
Labels: ci/cd, testing
