### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by marpio** [gomods/athens#1275] opened 2019-06-06 20:00 UTC
**Describe the bug**
From a Slack conversation:
https://gophers.slack.com/archives/C9LRAQN8N/p1559819025026000

On one of my machines, Athens is returning 500s on all requests. Any suggestion how I could debug what happens ? 

**Error Message**
The docker log is full of lines like

```
time="2019-06-06T10:59:54Z" level=error msg="exit status 1: go: finding github.com/pkg/errors v0.8.1\n" http-method=GET http-path=/github.com/pkg/errors/@v/v0.8.1.info http-url=/github.com/pkg/errors/@v/v0.8.1.info kind="Internal Server Error" module=github.com/pkg/errors operation=download.InfoHandler ops="[download.InfoHandler pool.Info protocol.Info stash.Pool stasher.Stash stasher.fetchModule goGetFetcher.Fetch module.downloadModule]" version=v0.8.1
```

**Environment (please complete the following information):**
 - OS: ubuntu 18.04.2 
 - Go version : Go 1.12.5
 - Proxy version : v0.4.0
 - Storage (fs/mongodb/s3 etc.) :

**Additional context**
this happens both on v0.4.0, latest and canary; machine is ubuntu 18.04.2 ; I have no issue on my macOS machines. Go 1.12.5
`go mod download module@version` works on that machine if `GOPROXY` is not set.
 when I tried to `go mod vendor`, in addition to the errors, the athens log said:

```
"go list -m github.com/spf13/viper: git ls-remote -q origin in /tmp/athens170084170/pkg/mod/cache/vcs/5fb3e42b1f6052aa08228f623b105973cd6121a1343230bfc0bf4b47f3528c7e: exit status 128:\n\tfatal: unable to access 'https://github.com/spf13/viper/': Could not resolve host: github.com\n" http-method=GET http-path=/github.com/spf13/viper/@v/list http-url=/github.com/spf13/viper/@v/list kind="Internal Server Error" module= operation=download.ListHandler ops="[download.ListHandler pool.List protocol.List vcsLister.List]" version="  
```
saying it "Could not resolve host: github.com", although `nslookup github.com` works.

**Comment by fgm** [comment] 2019-06-06 20:03
Thanks for doing it for me. Of course, the error starts by "go list...", not just "o list...", it was a paste error.

**Comment by chen56** [comment] 2019-06-18 11:10
gomods/athens:latest , same error???

```bash
go-mod-proxy-athens | time="2019-06-18T10:38:56Z" level=error msg="exit status 1: go list -m golang.org/x/sync: git ls-remote -q origin in /tmp/athens881117776/pkg/mod/cache/vcs/55179c5d8c4db2eaed9fae4682d4c84a1fd3612df666b372bef3bbb997c9601f: exit status 128:\n\tfatal: unable to access 'https://go.googlesource.com/sync/': Failed to connect to go.googlesource.com port 443: Connection refused\n" http-method=GET http-path=/golang.org/x/sync/@v/list http-url=/golang.org/x/sync/@v/list kind="Internal Server Error" module= operation=download.ListHandler ops="[download.ListHandler pool.List protocol.List vcsLister.List]" version=
```

but, gomods/athens:v0.3.1 is ok!


dock-compose config:

services:
  athens:
    image: gomods/athens:v0.3.1
    ports:
      - 3001:3000
    container_name: go-mod-proxy-athens
    environment:
      - ATHENS_DISK_STORAGE_ROOT=/app/storage
      - ATHENS_NETRC_PATH=/app/.netrc
      - ATHENS_STORAGE_TYPE=disk
      - HTTP_PROXY=http://192.168.1.20:8118
      - HTTPS_PROXY=http://192.168.1.20:8118
    volumes:
      - ./:/app

**Comment by lowstz** [comment] 2019-08-06 10:56
500 errors happens both on v0.4.0 and v.0.5.0 release

@chen56 rollback to v0.3.1 fix the issue, Thank you!

**Comment by samzhao88** [comment] 2019-09-05 02:10
I also run into the same issue with v0.5.0. 
Any updates on this?

**Comment by draeron** [comment] 2019-09-09 18:29
> I also run into the same issue with v0.5.0.
> Any updates on this?

I'm pretty this is caused by go 1.13 as mentionned here https://github.com/gomods/athens/issues/1372

**Comment by marwan-at-work** [comment] 2019-10-17 01:32
Can people here struggling with this try it with the latest Athens version? `v0.6.1` 

Thanks

**Comment by marwan-at-work** [comment] 2019-10-17 01:33
Closing ,since it seems like a duplicate of 1372 but pls feel free to re-open

**Closed by marwan-at-work** 2019-10-17 01:33 UTC
Labels: bug, question

**Comment by arschles** [comment] 2019-10-18 03:04
#1372 to get the link into that issue
