### ISSUE TITLE
wish support go get with branchname

### ISSUE THREAD

**Issue by stubbornTanzhe** [gomods/athens#949] opened 2018-11-27 04:00 UTC
**Is your feature request related to a problem? Please describe.**

in my company,every private project has the branch include "develop","test","pre-production" and "master".first we write code to "develop" branch the merge from "develop" to "test",and to "master" in the end.
so the code I depend on always first in "develop" branch.so i need to go get project_i_depend@develop.
With the origin go command,i can use go get project@develop and the data return with develop branch correspond to which commit and return the right code i need.

but with athens and proxy,i can only get the code with master branch,not the branch i need.

**Describe the solution you'd like**
when i use go get XXX-project@XXX-branch,i get the branch code to download
athens can handle the "branch go get" and return the right data

**Describe alternatives you've considered**
now no solution

**Additional context**

**Comment by marpio** [comment] 2018-11-27 15:46
@stubbornTanzhe  this is a [known limitation](https://docs.gomods.io/intro/known-limitations/) Documentation mentions commit hash but it applies also to branches.
What you can do is `go get` this module without using proxy (so GOPROXY="") 
For example `go get github.com/juju/errors@master` will add something like `require github.com/juju/errors v0.0.0-20181118221551-089d3ea4e4d5 // indirect` to the `go.mod` file. The build using proxy will work because now the proxy will use the pseudo-version ` v0.0.0-20181118221551-089d3ea4e4d5`.
Ref https://github.com/golang/go/issues/27947

**Comment by arschles** [comment] 2018-12-06 19:18
I'm going to close this as a duplicate of #950, because that's a superset of this one

**Closed by arschles** 2018-12-06 19:18 UTC
Labels: bug, proposal
