### ISSUE TITLE
Write docs to indicate that you can't get a package by revision

### ISSUE THREAD

**Issue by arschles** [gomods/athens#822] opened 2018-10-25 18:47 UTC
**Is your feature request related to a problem? Please describe.**
The problem is in #699 

**Describe the solution you'd like**
We should write docs to explain #699

**Describe alternatives you've considered**
None

**Additional context**
We discussed doing this in the Oct. 25 2018 Development Meeting

**Comment by marpio** [comment] 2018-10-25 19:06
@arschles isn't this a duplicate of #819 ?

**Comment by marpio** [comment] 2018-10-26 18:30
@fedepaol that would be great but unfortunately the go cmd doesn't give any meaningful error msg so we would have to check if it's a semver/pseudo version or not. Not sure how to do that without copying a bunch of go code...

**Comment by fedepaol** [comment] 2018-10-26 18:42
@marpio , I feel like we already had this discussion, but isn't it enough to look for pseudoversions (as we already do in https://github.com/gomods/athens/blob/master/pkg/middleware/filter.go#L54 ) or versions (matchable by a regex) and reject otherwise?

**Comment by arschles** [comment] 2018-10-30 17:44
cc/ @marwan-at-work - he might have some opinions on the reporting part as well

**Comment by fedepaol** [comment] 2018-10-30 21:58
Just my 2 cents, but if a self explaining error is easy to implement (and I think it is), it will result in a better user experience and will prevent us to answer to a lot of "RTM" issues. I don't believe all the users will read through all the docs.

**Comment by marpio** [comment] 2018-10-31 15:23
Just for reference (copied from go):

```
// The general form of a semantic version string accepted by this package is
//
//	vMAJOR[.MINOR[.PATCH[-PRERELEASE][+BUILD]]]
//
// where square brackets indicate optional parts of the syntax;
// MAJOR, MINOR, and PATCH are decimal integers without extra leading zeros;
// PRERELEASE and BUILD are each a series of non-empty dot-separated identifiers
// using only alphanumeric characters and hyphens; and
// all-numeric PRERELEASE identifiers must not have leading zeros.
//
// This package follows Semantic Versioning 2.0.0 (see semver.org)
// with two exceptions. First, it requires the "v" prefix. Second, it recognizes
// vMAJOR and vMAJOR.MINOR (with no prerelease or build suffixes)
// as shorthands for vMAJOR.0.0 and vMAJOR.MINOR.0.
```

**Closed** 2018-11-02 15:10 UTC
Labels: docs
