### ISSUE TITLE
404 for gopkg.in/russross/blackfriday.v2

### ISSUE THREAD

**Issue by xytan0056** [gomods/athens#1489] opened 2019-12-06 23:37 UTC
**Describe the bug**
This is a weird one 

```
$ GOPRIVATE=* GONOPROXY=none GOPROXY=http://localhost:3000  GO111MODULE=on go1.13 get gopkg.in/russross/blackfriday.v2
go: finding gopkg.in/russross/blackfriday.v2 v2.0.1
go get gopkg.in/russross/blackfriday.v2: gopkg.in/russross/blackfriday.v2@v2.0.1: reading http://localhost:3000/gopkg.in/russross/blackfriday.v2/@v/v2.0.1.info: 404 Not Found

$ GOPRIVATE=* GONOPROXY=none 
GOPROXY=https://proxy.golang.org  GO111MODULE=on go1.13 get gopkg.in/russross/blackfriday.v2
```
but 
https://proxy.golang.org/gopkg.in/russross/blackfriday.v2/@v/v2.0.1.info
looks like 410 in google's proxy as well

but difference is return code, athens return 404

**To Reproduce**
`GOPRIVATE=* GONOPROXY=none GOPROXY=http://localhost:3000  GO111MODULE=on go1.13 get gopkg.in/russross/blackfriday.v2`

**Comment by arschles** [comment] 2019-12-12 18:57
@xytan0056 is Athens configured with [`GoNoSumDB`](https://docs.gomods.io/configuration/sumdb/)?

**Comment by arschles** [comment] 2019-12-12 18:58
Also, our return codes are slightly different than the Google proxy because we don't parse the `go` CLI tool's output the same. Do you require that we return the same HTTP error codes as the Google proxy?

**Comment by xytan0056** [comment] 2019-12-13 01:09
I'm not sure. what would be the root cause for this module

https://proxy.golang.org/gopkg.in/russross/blackfriday.v2/@v/list
returns fine

athens doesn't
$ curl -I http://localhost:3000/gopkg.in/russross/blackfriday.v2/@v/list
HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Date: Fri, 13 Dec 2019 01:09:22 GMT

**Comment by arschles** [comment] 2019-12-13 23:33
@xytan0056 it looks like the go.mod for this module in github is saying the module is `github.com/russross/blackfriday/v2`, but you're requesting it as the `gopkg.in/russross/blackfriday.v2`. I replicated that below.

I'm betting that `proxy.golang.org` has this module in its own internal storage from when it had the right name in its `go.mod`

```console
ecomaz :: Samsung_T5/code/assert ‹master*› » export GOPROXY=direct
ecomaz :: Samsung_T5/code/assert ‹master*› » sudo rm -rf ~/gocode/pkg/mod
ecomaz :: Samsung_T5/code/assert ‹master*› » go get gopkg.in/russross/blackfriday.v2
go: finding gopkg.in/russross/blackfriday.v2 v2.0.1
go get gopkg.in/russross/blackfriday.v2: gopkg.in/russross/blackfriday.v2@v2.0.1: invalid version: go.mod has non-....v2 module path "github.com/russross/blackfriday/v2" at revision v2.0.1
```

To fix this, can you use a `redirect` rule in the [download mode file](https://docs.gomods.io/configuration/download/)?

Long term, https://github.com/gomods/athens/issues/1488 could help with this specific problem, and https://github.com/gomods/athens/issues/1315 could help (if we can figure it out) with doing renames.

**Comment by arschles** [comment] 2020-02-20 02:33
@xytan0056 have you found a way to fix this with the download mode file?

I am going to close this issue now, but please comment here if the issue is not fixed. I will get a notification that you commented, reopen it, and continue our discussion.

**Closed by arschles** 2020-02-20 02:33 UTC

**Comment by xytan0056** [comment] 2020-02-20 19:48
We did the same -- stash the old module. For now it's fine. Thanks for the tips about download mod. I will try it out

**Comment by arschles** [comment] 2020-02-20 22:24
You got it @xytan0056. If you have more questions, we will always be here to help 😄
